### Numpy -> para trabalhar com sequências de elementos de forma mais otimizada que demais funcionalidades built-in do Python

In [1]:
import sys
import numpy as np
print(sys.version, '\n')
np.__version__

3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] 



'1.11.3'

In [2]:
array7 = np.arange(0,30,2)
print('imprimindo array original (array7):')
print(array7, '\n')

print('imprimindo operações matemáticas sobre o array do Numpy:')
print('média dos elementos do array:', array7.mean())
print('soma dos elementos do array:', array7.sum())
print('valor mínnimo:', array7.min())
print('valor máximo:', array7.max())
print('desvio padrão:', array7.std())

imprimindo array original (array7):
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28] 

imprimindo operações matemáticas sobre o array do Numpy:
média dos elementos do array: 14.0
soma dos elementos do array: 210
valor mínnimo: 0
valor máximo: 28
desvio padrão: 8.64098759788


### Utilizando List Comprehension em Arrays Numpy

In [3]:
print('imprimindo array original (array7):')
print(array7, '\n')

print('imprimindo uma list comprehension com numpy, tendo o conjunto de dados o array7:')
print([x**2 for x in array7], '\n')

print('imprimindo uma list comprehension com numpy, tendo o conjunto de dados o array7 + predicado (valores >= 18):')
print(' array com valores >= 18 ------->', [x for x in array7 if x >= 18])
print('[array com valores >= 18]**2 --->', [x**2 for x in array7 if x >= 18])

imprimindo array original (array7):
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28] 

imprimindo uma list comprehension com numpy, tendo o conjunto de dados o array7:
[0, 4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784] 

imprimindo uma list comprehension com numpy, tendo o conjunto de dados o array7 + predicado (valores >= 18):
 array com valores >= 18 -------> [18, 20, 22, 24, 26, 28]
[array com valores >= 18]**2 ---> [324, 400, 484, 576, 676, 784]


### Utilizando Função Lambda em Arrays Numpy

In [4]:
array8 = np.arange(3,66,7)
print('imprimindo array original (array8):')
print(array8, '\n')

print('A) imprimindo valores de um processamento de ums função lambda, onde os dados são oriundos de um array Numpy (array8):')
print(list(filter(lambda x: x % 2 == 0, array8)), '\n')

print('executando a mesma função acima, porém utilizando uma funcionalidade do próprio NUMPY:')
print('ATENÇÃO!!!','\n')
print('lista de valores BOOLENOS que compreende a operação em Numpy -> array8 % 2 == 0')
print(array8 % 2 == 0, '\n')

print('B) lista de valores que compreende a operação em Numpy, porém com notação em ÍNDICE -> array8[array8 % 2 == 0]:')
print(array8[array8 % 2 == 0])

imprimindo array original (array8):
[ 3 10 17 24 31 38 45 52 59] 

A) imprimindo valores de um processamento de ums função lambda, onde os dados são oriundos de um array Numpy (array8):
[10, 24, 38, 52] 

executando a mesma função acima, porém utilizando uma funcionalidade do próprio NUMPY:
ATENÇÃO!!! 

lista de valores BOOLENOS que compreende a operação em Numpy -> array8 % 2 == 0
[False  True False  True False  True False  True False] 

B) lista de valores que compreende a operação em Numpy, porém com notação em ÍNDICE -> array8[array8 % 2 == 0]:
[10 24 38 52]


### Performance - List Comprehension X Numpy

In [8]:
#List Comprehension
import numpy as np

#List Comprehension
array9 = np.arange(3,300,7)
print('imprimindo array original (array9):')
print(list(array9), '\n')

print('Executando operação para teste de performance com NUMPY...', '\n')
print([(x**2)/2 for x in array9 if x % 2 == 0], '\n')

%timeit [(x**2)/2 for x in array9 if x % 2 == 0]

imprimindo array original (array9):
[3, 10, 17, 24, 31, 38, 45, 52, 59, 66, 73, 80, 87, 94, 101, 108, 115, 122, 129, 136, 143, 150, 157, 164, 171, 178, 185, 192, 199, 206, 213, 220, 227, 234, 241, 248, 255, 262, 269, 276, 283, 290, 297] 

Executando operação para teste de performance com NUMPY... 

[50.0, 288.0, 722.0, 1352.0, 2178.0, 3200.0, 4418.0, 5832.0, 7442.0, 9248.0, 11250.0, 13448.0, 15842.0, 18432.0, 21218.0, 24200.0, 27378.0, 30752.0, 34322.0, 38088.0, 42050.0] 

100000 loops, best of 3: 16.5 µs per loop


In [7]:
#Numpy
import numpy as np

#List Comprehension
array10 = np.arange(3,300,7)
print('imprimindo array original (array10):')
print(list(array10), '\n')

print('Executando operação para teste de performance com NUMPY...', '\n')
print(((array10[array10 % 2 == 0])**2)/2, '\n')

%timeit ((array9[array9 % 2 == 0])**2)/2

imprimindo array original (array10):
[3, 10, 17, 24, 31, 38, 45, 52, 59, 66, 73, 80, 87, 94, 101, 108, 115, 122, 129, 136, 143, 150, 157, 164, 171, 178, 185, 192, 199, 206, 213, 220, 227, 234, 241, 248, 255, 262, 269, 276, 283, 290, 297] 

Executando operação para teste de performance com NUMPY... 

[    50.    288.    722.   1352.   2178.   3200.   4418.   5832.   7442.
   9248.  11250.  13448.  15842.  18432.  21218.  24200.  27378.  30752.
  34322.  38088.  42050.] 

The slowest run took 21.34 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.73 µs per loop


### Usando operadores lógicos

In [37]:
#Numpy
import numpy as np

array11 = np.arange(100,300,9)
print('imprimindo array original (array11):')
print(list(array11), '\n')

print('comparando se valores do array atendem ou não uma condição de um operdor lógico (array11 > 200):')
print(array11 > 200, '\n')

print('Array como uma condição de índice, onde dentro da notação de índice, o resultado são os elementos que atendem')
print('aquela condição (array11[array11>200])')
print(array11[array11>200],'\n')

print('operador lógico E (&) em relação ao array original (array11>150) & (array11<200):')
print((array11>150) & (array11<200), '\n')

print('operador lógico OU (|) em relação ao array original (array11>200) | (array11<149):')
print((array11>200) | (array11<149), '\n')

print('operador lógico E (&) como notação de indice array11[(array11>150) & (array11<200)]:')
print(array11[(array11>150) & (array11<200)], '\n')

print('criando um array numpy usando list compreenhension (np.array([x*2 for x in np.arange(150,300,20)]):')
array12 = np.array([x*2 for x in np.arange(150,300,20)])
print(array12)



imprimindo array original (array11):
[100, 109, 118, 127, 136, 145, 154, 163, 172, 181, 190, 199, 208, 217, 226, 235, 244, 253, 262, 271, 280, 289, 298] 

comparando se valores do array atendem ou não uma condição de um operdor lógico (array11 > 200):
[False False False False False False False False False False False False
  True  True  True  True  True  True  True  True  True  True  True] 

Array como uma condição de índice, onde dentro da notação de índice, o resultado são os elementos que atendem
aquela condição (array11[array11>200])
[208 217 226 235 244 253 262 271 280 289 298] 

operador lógico E (&) em relação ao array original (array11>150) & (array11<200):
[False False False False False False  True  True  True  True  True  True
 False False False False False False False False False False False] 

operador lógico OU (|) em relação ao array original (array11>200) | (array11<149):
[ True  True  True  True  True  True False False False False False False
  True  True  True  True  T

### Concatenando arrays

In [42]:
import numpy as np

print('imprimindo array12 original')
array12 = np.arange(0,10,1)
print(array12, '\n')

print('imprimindo array13 original')
array13 = np.zeros(10)
print(array13, '\n')

print('concatenando array12 com array 13')
array_concat = np.concatenate((array12, array13))
print(array_concat)

imprimindo array12 original
[0 1 2 3 4 5 6 7 8 9] 

imprimindo array13 original
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.] 

concatenando array12 com array 13
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.]


### Join Arrays

In [65]:
import numpy as np

print('imprimindo matriz "v" original')
v = np.array([['x', 'y', 'z'], ['a', 'b', 'c'], ['j', 'k', 'l']])
print(v, '\n')

print('imprimindo matriz "v" original')
z = np.zeros((3,3))
print(z, '\n')

#np.vstack - organizção de colunas entre arrays
print('imprimindo concatenação VERTICAL entre as matrizes "v" e "z" (np.vstack)')
print(np.vstack((v, z)),'\n')

#np.hstack - organizção de linhas entre arrays
print('imprimindo concatenação VERTICAL entre as matrizes "v" e "z" (np.hstack)')
print(np.hstack((v, z)),'\n')

print('imprimindo array14 original')
array14 = np.array(["e", "rr", "tt", "gf"])
print(array14, '\n')
print('imprimindo array15 original')
array15 = np.array([1.23, 55.6, 85.44, 22.74])
print(array15, '\n')
print('imprimindo array16 original')
array16 = np.array(["banana", "maçã", "pêra", "abacaxi"])
print(array16, '\n')

print('imprimindo concatenação VERTICAL entre as os arrays: array14, array15, array16 (np.column_stack)')
print(np.column_stack((array14, array15, array16)),'\n')

print('imprimindo concatenação HORIZONTAL entre as os arrays: array14, array15, array16 (np.row_stack)')
print(np.row_stack((array14, array15, array16)),'\n')

imprimindo matriz "v" original
[['x' 'y' 'z']
 ['a' 'b' 'c']
 ['j' 'k' 'l']] 

imprimindo matriz "v" original
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]] 

imprimindo concatenação VERTICAL entre as matrizes "v" e "z" (np.vstack)
[['x' 'y' 'z']
 ['a' 'b' 'c']
 ['j' 'k' 'l']
 ['0.0' '0.0' '0.0']
 ['0.0' '0.0' '0.0']
 ['0.0' '0.0' '0.0']] 

imprimindo concatenação VERTICAL entre as matrizes "v" e "z" (np.hstack)
[['x' 'y' 'z' '0.0' '0.0' '0.0']
 ['a' 'b' 'c' '0.0' '0.0' '0.0']
 ['j' 'k' 'l' '0.0' '0.0' '0.0']] 

imprimindo array14 original
['e' 'rr' 'tt' 'gf'] 

imprimindo array15 original
[  1.23  55.6   85.44  22.74] 

imprimindo array16 original
['banana' 'maçã' 'pêra' 'abacaxi'] 

imprimindo concatenação VERTICAL entre as os arrays: array14, array15, array16 (np.column_stack)
[['e' '1.23' 'banana']
 ['rr' '55.6' 'maçã']
 ['tt' '85.44' 'pêra']
 ['gf' '22.74' 'abacaxi']] 

imprimindo concatenação HORIZONTAL entre as os arrays: array14, array15, array16 (np.row_stack)
[['e' 'rr' 'tt' '

### Split Arrays

In [5]:
import numpy as np

array17 = np.arange(110,270,10).reshape(4,4)

print('imprimindo o array17 original:')
print(array17, '\n', 'shape: ', array17.shape, '\n')

print('dividindo o array17 ORIGINAL em duas partes, por SEQUÊNCIA DE COLUNAS (np.hsplit):')
[array17_hparte1, array17_hparte2] = np.hsplit(array17, 2)
print('parte 1 do array17', '\n', array17_hparte1, '\n')
print('parte 2 do array17', '\n', array17_hparte2, '\n')

print('dividindo o array17 ORIGINAL em duas partes, por SEQUÊNCIA DE LINHAS (np.vsplit):')
[array17_vparte1, array17_vparte2] = np.vsplit(array17, 2)
print('parte 1 do array17', '\n', array17_vparte1, '\n')
print('parte 2 do array17', '\n', array17_vparte2, '\n')

imprimindo o array17 original:
[[110 120 130 140]
 [150 160 170 180]
 [190 200 210 220]
 [230 240 250 260]] 
 shape:  (4, 4) 

dividindo o array17 ORIGINAL em duas partes, por SEQUÊNCIA DE COLUNAS (np.hsplit):
parte 1 do array17 
 [[110 120]
 [150 160]
 [190 200]
 [230 240]] 

parte 2 do array17 
 [[130 140]
 [170 180]
 [210 220]
 [250 260]] 

dividindo o array17 ORIGINAL em duas partes, por SEQUÊNCIA DE LINHAS (np.vsplit):
parte 1 do array17 
 [[110 120 130 140]
 [150 160 170 180]] 

parte 2 do array17 
 [[190 200 210 220]
 [230 240 250 260]] 



### Gravando e Carregando Dados em Numpy

In [17]:
import numpy as np

dados = np.arange(110,270,10).reshape(4,4)

print('salvando os dados de uma matriz em um arquivo externo...', '\n')
np.save('dados_matriz.npy', dados) #npy é a extensão de um record set em numpy

print('carregando os dados de um arquivo externo que contêm uma matriz para uma variável...', '\n')
carrega_arquivo = np.load('dados_matriz.npy')

print(carrega_arquivo)

salvando os dados de uma matriz em um arquivo externo... 

carregando os dados de um arquivo externo que contêm uma matriz para uma variável... 

[[110 120 130 140]
 [150 160 170 180]
 [190 200 210 220]
 [230 240 250 260]]


### Matrizes com Numpy - 2 dimensões
### Criando Matrizes

In [33]:
matrix1 = np.matrix("55, 21, 32; 99, 10, 8")
print(' conteúdo da matrix1', '\n\n', matrix1, '\n', 'shape:', matrix1.shape, '\n', 'type:', type(matrix1), '\n')

matrix2 = np.matrix([[22,33,11], [44,55,66], [99,88,77]])
print(' conteúdo da matrix2:', '\n\n', matrix2, '\n\n', 'shape:', matrix2.shape, '\n', 'type:', type(matrix2))

 conteúdo da matrix1 

 [[55 21 32]
 [99 10  8]] 
 shape: (2, 3) 
 type: <class 'numpy.matrixlib.defmatrix.matrix'> 

 conteúdo da matrix2: 

 [[22 33 11]
 [44 55 66]
 [99 88 77]] 

 shape: (3, 3) 
 type: <class 'numpy.matrixlib.defmatrix.matrix'>


#### Slicing de matrizes

In [88]:
matrix3 = np.matrix("65, 11, 45; 49, 14, 18; 10, 20, 30; 65, 64, 64")
print(' conteúdo da matrix3', '\n\n', matrix3, '\n\n', 'shape:', matrix3.shape, '\n', 'type:', type(matrix3), '\n')

#print(' slicing :', '\n', matrix3[1:2])
matrix3[1:3,1:]

 conteúdo da matrix3 

 [[65 11 45]
 [49 14 18]
 [10 20 30]
 [65 64 64]] 

 shape: (4, 3) 
 type: <class 'numpy.matrixlib.defmatrix.matrix'> 



matrix([[14, 18],
        [20, 30]])

### Matriz Esparsa -> em numpy basicamente é um conj. de arrays interligados, na qual a grande maioria dos seus elementos possui um valor padrão (exemplo: zero) ou são nulos ou faltantes.

#### depende da biblioteca scipy.sparse

In [160]:
import numpy as np
import scipy.sparse

print('criando uma MATRIZ ESPARSA representada na diagonal pelos valores = np.array([115, 60, 55, 234] ...', '\n')
print('shape escolhido: 4 linhas X 4 colunas', '\n')
linhas = np.array([0, 1, 2, 3])
colunas = np.array([0, 1, 2, 3])
valores = np.array([115, 60, 55, 234])

matrix_esparsa1 = scipy.sparse.coo_matrix((valores, (linhas, colunas)))
print('imprimindo a matriz esparsa (scipy.sparse.MATRIX.toarray())...')
print(matrix_esparsa1.toarray(), '\n\n', 'shape', '\n', matrix_esparsa1.shape, '\n')
print(matrix_esparsa1, '\n\n')

print('Verificando se o objeto criado ("matrix_esparsa1") é uma matriz esparsa:')
print(scipy.sparse.isspmatrix(matrix_esparsa1))

criando uma MATRIZ ESPARSA representada na diagonal pelos valores = np.array([115, 60, 55, 234] ... 

shape escolhido: 4 linhas X 4 colunas 

imprimindo a matriz esparsa (scipy.sparse.MATRIX.toarray())...
[[115   0   0   0]
 [  0  60   0   0]
 [  0   0  55   0]
 [  0   0   0 234]] 

 shape 
 (4, 4) 

  (0, 0)	115
  (1, 1)	60
  (2, 2)	55
  (3, 3)	234 


Verificando se o objeto criado ("matrix_esparsa1") é uma matriz esparsa:
True


### Operações com Arrays e Matrizes

In [208]:
import numpy as np

array18 = np.array([[10,2,3], [1,4,2], [10,2,1]])
print('imprimindo o array18 original:', '\n')
print(array18, '\n\n', 'shape:', array18.shape, '\n', 'type:', type(array18), '\n')

array19 = np.array([[2,3,1], [1,5,3], [2,5,4]])
print('imprimindo o array19 original:', '\n')
print(array19, '\n\n', 'shape:', array19.shape, '\n', 'type:', type(array19), '\n')

print('MULTIPLICAÇÃO de ARRAYS: array18 * array19', '\n')
print('*---> lembrando que multiplicações entre ARRAYS é proposta elemento por elemento. Ex.: elemento da')
print('da linha 1 coluna 1 do array18 vai multiplicar com elemento linha 1 coluna 1 do array19, e assim')
print('sucessivamente para todos os elementos. A nova matriz gerada será a multiplicação entre ambas.')
array20 = array18 * array19
print(array20, '\n\n', 'type:', type(array20), '\n')

print('----------------------', '\n')

print('gerando uma MATRIZ à partir dos dados do array18')
matrix4 = np.mat(array18)
print('Imprimindo matrix4', '\n', matrix4, '\n\n', 'shape:', matrix4.shape, '\n', 'type:', type(matrix4), '\n\n')

print('gerando uma MATRIZ à partir dos dados do array19')
matrix5 = np.mat(array19)
print('Imprimindo matrix5', '\n', matrix5, '\n\n', 'shape:', matrix5.shape, '\n', 'type:', type(matrix5), '\n\n')

print('MULTIPLICAÇÃO de MATRIZES: matrix4 * matrix5')
print('*---> lembrando que multiplicações entre matrizes são todos os elementos da linha da matriz A[i:j]')
print('X todos os elementos da coluna da matriz B[i:j], onde i=linha e j=coluna', '\n')
matrix6 = matrix4 * matrix5
print(matrix6, '\n\n', 'shape:', matrix4.shape, '\n\n', 'type:', type(matrix6), '\n')

imprimindo o array18 original: 

[[10  2  3]
 [ 1  4  2]
 [10  2  1]] 

 shape: (3, 3) 
 type: <class 'numpy.ndarray'> 

imprimindo o array19 original: 

[[2 3 1]
 [1 5 3]
 [2 5 4]] 

 shape: (3, 3) 
 type: <class 'numpy.ndarray'> 

MULTIPLICAÇÃO de ARRAYS: array18 * array19 

*---> lembrando que multiplicações entre ARRAYS é proposta elemento por elemento. Ex.: elemento da
da linha 1 coluna 1 do array18 vai multiplicar com elemento linha 1 coluna 1 do array19, e assim
sucessivamente para todos os elementos. A nova matriz gerada será a multiplicação entre ambas.
[[20  6  3]
 [ 1 20  6]
 [20 10  4]] 

 type: <class 'numpy.ndarray'> 

---------------------- 

gerando uma MATRIZ à partir dos dados do array18
Imprimindo matrix4 
 [[10  2  3]
 [ 1  4  2]
 [10  2  1]] 

 shape: (3, 3) 
 type: <class 'numpy.matrixlib.defmatrix.matrix'> 


gerando uma MATRIZ à partir dos dados do array19
Imprimindo matrix5 
 [[2 3 1]
 [1 5 3]
 [2 5 4]] 

 shape: (3, 3) 
 type: <class 'numpy.matrixlib.defmatrix

In [219]:
import numpy as np

print('Caso queira que o ARRAY tenha o mesmo comportamento matemático da MATRIZ, usa-se a função np.dot() do numpy')
print('\n')

array21 = np.array([[10,2,3], [1,4,2], [10,2,1]])
print('imprimindo o array21 original:', '\n')
print(array21, '\n\n', 'shape:', array21.shape, '\n', 'type:', type(array21), '\n')

array22 = np.array([[2,3,1], [1,5,3], [2,5,4]])
print('imprimindo o array22 original:', '\n')
print(array22, '\n\n', 'shape:', array22.shape, '\n', 'type:', type(array22), '\n')

print('imprimindo uma MULTIPLICAÇÃO entre arrays (array21 * array22), considerando o')
print('mesmo comportamento matemático de uma matriz:', '\n')
array23 = np.dot(array21, array22)
print(array23, '\n\n', 'shape:', array23.shape, '\n', 'type:', type(array23), '\n')

print('gerando uma MATRIZ à partir dos dados do array23')
matrix6 = np.mat(array23)
print('Imprimindo matrix6', '\n', matrix6, '\n\n', 'shape:', matrix6.shape, '\n', 'type:', type(matrix6), '\n\n')

print('convertendo a MATRIZ (matrix6) para um ARRAY:')
array24 = np.asarray(matrix6)
print('Imprimindo matrix6', '\n', array24, '\n\n', 'shape:', array24.shape, '\n', 'type:', type(array24), '\n\n')

Caso queira que o ARRAY tenha o mesmo comportamento matemático da MATRIZ, usa-se a função np.dot() do numpy


imprimindo o array21 original: 

[[10  2  3]
 [ 1  4  2]
 [10  2  1]] 

 shape: (3, 3) 
 type: <class 'numpy.ndarray'> 

imprimindo o array22 original: 

[[2 3 1]
 [1 5 3]
 [2 5 4]] 

 shape: (3, 3) 
 type: <class 'numpy.ndarray'> 

imprimindo uma MULTIPLICAÇÃO entre arrays (array21 * array22), considerando o
mesmo comportamento matemático de uma matriz: 

[[28 55 28]
 [10 33 21]
 [24 45 20]] 

 shape: (3, 3) 
 type: <class 'numpy.ndarray'> 

gerando uma MATRIZ à partir dos dados do array23
Imprimindo matrix6 
 [[28 55 28]
 [10 33 21]
 [24 45 20]] 

 shape: (3, 3) 
 type: <class 'numpy.matrixlib.defmatrix.matrix'> 


convertendo a MATRIZ (matrix6) para um ARRAY:
Imprimindo matrix6 
 [[28 55 28]
 [10 33 21]
 [24 45 20]] 

 shape: (3, 3) 
 type: <class 'numpy.ndarray'> 




### Vetorização (Numpy) -> ganho de performance ao aplicar uma FUNÇÃO a um conjunto de elementos (similar ao map() e o filter()). Para esses casos, evite usar loop for.

### Nesse caso, a função numpy.vetorize vetoriza a DEF (definição de função ao qual recebe parâmetros de entrada), para que essa consiga receber como parâmetro um array de elementos.

In [110]:
import numpy as np

array25 = np.random.randint(3,60,15)
print('imprimindo o array25 original:', '\n')
print(array25, '\n\n', 'shape:', array25.shape, '\n', 'type:', type(array25), '\n')

def cal_num(numero):
    if numero % 2==0:
        return (numero/2)
    else:
        return (numero/3)

imprimindo o array25 original: 

[45 48 46 18 57  3  8 18 16 50 24 56 41  6 45] 

 shape: (15,) 
 type: <class 'numpy.ndarray'> 



In [111]:
print('passando o array25 à função cal_num definida anteriormente:')
print('(espera-se um erro, pois a função espera que seja passado um elemento de cada vez, e não todo o array)')
cal_num(array25)

passando o array25 à função cal_num definida anteriormente:
(espera-se um erro, pois a função espera que seja passado um elemento de cada vez, e não todo o array)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [120]:
import numpy as np

print('vetorizando a função [cal_num] para que um array de elementos possa ser passado como parâmetro...')
print('--->>> np.vectorize(função)')
vetorizacao_function1 = np.vectorize(cal_num)

print('type do objeto vetorizado:', type(vetorizacao_function1))
print(vetorizacao_function1, '\n')

print('imprimindo o array25 original:', '\n')
print(array25, '\n\n', 'shape:', array25.shape, '\n', 'type:', type(array25), '\n')

print('Aplicando cada um dos elementos do [array25] à FUNÇÃO VETORIZADA [vetorizacao_function1(num)].')
print('Após isso, lista dentro de um array gerado os respectivos resultados da aplicação da função em relação aos', '\n')
print('elementos do array25:')
print(vetorizacao_function1(array25), '\n')

print('usando o MAP para fazer a mesma vetorização entre a função ORIGINAL [cal_num] e os elementos do array [array25],')
print('jogando o resultado ITERABLE do MAP em uma lista de elementos:')
print(list(map(cal_num,array25)), '\n')

print('usando LIST COMPREHENSION para fazer a mesma vetorização entre a função ORIGINAL [cal_num] e os elementos')
print('do array [array25]:')
print([cal_num(x) for x in array25], '\n')

vetorizando a função [cal_num] para que um array de elementos possa ser passado como parâmetro...
--->>> np.vectorize(função)
type do objeto vetorizado: <class 'numpy.lib.function_base.vectorize'>

imprimindo o array25 original: 

[45 48 46 18 57  3  8 18 16 50 24 56 41  6 45] 

 shape: (15,) 
 type: <class 'numpy.ndarray'> 

Aplicando cada um dos elementos do [array25] à FUNÇÃO VETORIZADA [vetorizacao_function1(num)].
Após isso, lista dentro de um array gerado os respectivos resultados da aplicação da função em relação aos 

elementos do array25:
[ 15.          24.          23.           9.          19.           1.           4.
   9.           8.          25.          12.          28.          13.66666667
   3.          15.        ] 

usando o MAP para fazer a mesma vetorização entre a função ORIGINAL [cal_num] e os elementos do array [array25],
jogando o resultado ITERABLE do MAP em uma lista de elementos:
[15.0, 24.0, 23.0, 9.0, 19.0, 1.0, 4.0, 9.0, 8.0, 25.0, 12.0, 28.0, 13.666666

### Como saber qual das 3 maneiras é a mais performática? %timeit
#### - Vetorização com Numpy -> escolher essa solução quando a quantidade de elementos for realmente grande.
#### - Função map() -> para quantidade média de elementos em um array. Com breve vantagem sobre list comprehension.
#### - List Comprehension [ ] -> para quantidade média de elementos em um array. Apesar disso, na versão Python 3, recebeu melhorias significativas.

In [133]:
print('Qtd. elementos no [array25] = ', array25.size, '\n')

print('- Vetorização com Numpy - Aplicando a função VETORIZADA [vetorizacao_function1] para o [array25]')
%timeit(vetorizacao_function1(array25))
print('\n')

print('- Função map() - usando o MAP para fazer a mesma vetorização entre a função ORIGINAL [cal_num] e os elementos')
print(' do array [array25], jogando o resultado ITERABLE do MAP em uma lista de elementos:')
%timeit(list(map(cal_num,array25)))
print('\n')

print('- List Comprehension [ ] - usando LIST COMPREHENSION para fazer a mesma vetorização entre a função')
print(' ORIGINAL [cal_num] e os elementos do array [array25]:')
%timeit([cal_num(x) for x in array25])
print('\n')

Qtd. elementos no [array25] =  15 

- Vetorização com Numpy - Aplicando a função VETORIZADA [vetorizacao_function1] para o [array25]
The slowest run took 6.22 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 16.2 µs per loop


- Função map() - usando o MAP para fazer a mesma vetorização entre a função ORIGINAL [cal_num] e os elementos
 do array [array25], jogando o resultado ITERABLE do MAP em uma lista de elementos:
100000 loops, best of 3: 8.8 µs per loop


- List Comprehension [ ] - usando LIST COMPREHENSION para fazer a mesma vetorização entre a função
 ORIGINAL [cal_num] e os elementos do array [array25]:
100000 loops, best of 3: 9.07 µs per loop




In [134]:
print('Verificando performance')
print('Considerando um ARRAY [array26] com um NÚMERIO MAIOR DE ELEMENTOS em relação ao array25:', '\n')

array26 = np.random.randint(10, 500000, 50000)
print('Qtd. elementos no [array26] = ', array26.size, '\n')

print('- Vetorização com Numpy - Aplicando a função VETORIZADA [vetorizacao_function1] para o [array26]')
%timeit(vetorizacao_function1(array26))
print('\n')

print('- Função map() - usando o MAP para fazer a mesma vetorização entre a função ORIGINAL [cal_num] e os elementos')
print(' do array [array26], jogando o resultado ITERABLE do MAP em uma lista de elementos:')
%timeit(list(map(cal_num,array26)))
print('\n')

print('- List Comprehension [ ] - usando LIST COMPREHENSION para fazer a mesma vetorização entre a função')
print(' ORIGINAL [cal_num] e os elementos do array [array26]:')
%timeit([cal_num(x) for x in array26])
print('\n')

Verificando performance
Considerando um ARRAY [array26] com um NÚMERIO MAIOR DE ELEMENTOS em relação ao array25: 

Qtd. elementos no [array26] =  50000 

- Vetorização com Numpy - Aplicando a função VETORIZADA [vetorizacao_function1] para o [array26]
100 loops, best of 3: 13.3 ms per loop


- Função map() - usando o MAP para fazer a mesma vetorização entre a função ORIGINAL [cal_num] e os elementos
 do array [array26], jogando o resultado ITERABLE do MAP em uma lista de elementos:
10 loops, best of 3: 28.1 ms per loop


- List Comprehension [ ] - usando LIST COMPREHENSION para fazer a mesma vetorização entre a função
 ORIGINAL [cal_num] e os elementos do array [array26]:
10 loops, best of 3: 29.5 ms per loop




50000
